In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('Data/ucdp-brd-dyadic-211.csv')

In [5]:
df.head(5)

,conflict_id,dyad_id,location_inc,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,...,type_of_conflict,battle_location,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,gwno_battle,region,version
0,11447,10006,Ethiopia,Government of Ethiopia,97,NaN,IGLF,1115,NaN,1,...,3,Ethiopia,530,NaN,NaN,NaN,530,530,4,21.1
1,372,10054,Mali,Government of Mali,72,NaN,FPLA,934,NaN,1,...,3,Mali,432,NaN,NaN,NaN,432,432,4,21.1
2,283,10509,DR Congo (Zaire),Government of DR Congo (Zaire),89,"Government of Malawi, Government of South Afri...",APCLS,1200,NaN,2,...,4,DR Congo (Zaire),490,"553, 560, 510",NaN,NaN,490,490,4,21.1
3,283,10509,DR Congo (Zaire),Government of DR Congo (Zaire),89,"Government of Malawi, Government of South Afri...",APCLS,1200,NaN,2,...,4,DR Congo (Zaire),490,"553, 560, 510",NaN,NaN,490,490,4,21.1
4,283,10509,DR Congo (Zaire),Government of DR Congo (Zaire),89,"Government of Malawi, Government of South Afri...",APCLS,1200,NaN,2,...,4,DR Congo (Zaire),490,"553, 560, 510",NaN,NaN,490,490,4,21.1

In [12]:
df[df['year'] == 2019]

,conflict_id,dyad_id,location_inc,side_a,side_a_id,side_a_2nd,side_b,side_b_id,side_b_2nd,incompatibility,...,type_of_conflict,battle_location,gwno_a,gwno_a_2nd,gwno_b,gwno_b_2nd,gwno_loc,gwno_battle,region,version
10,13646,10589,Kenya,Government of Kenya,91,Government of United States of America,Al-Shabaab,717,NaN,1,...,4,Kenya,501,2,NaN,NaN,501,501,4,21.1
42,283,11377,DR Congo (Zaire),Government of DR Congo (Zaire),89,"Government of Malawi, Government of South Afri...",CNPSC,3043,NaN,2,...,4,DR Congo (Zaire),490,"553, 560, 510",NaN,NaN,490,490,4,21.1
45,223,11387,Myanmar (Burma),Government of Myanmar (Burma),144,NaN,ULA,3051,NaN,1,...,3,Myanmar (Burma),775,NaN,NaN,NaN,775,775,3,21.1
66,299,11973,Syria,Government of Syria,118,"Government of Iran, Government of Russia (Sovi...",Syrian insurgents,4456,NaN,2,...,4,Syria,652,"630, 365",NaN,NaN,652,652,2,21.1
111,374,12102,Rwanda,Government of Rwanda,94,Government of DR Congo (Zaire),FDLR,528,NaN,2,...,4,DR Congo (Zaire),517,490,NaN,NaN,517,490,4,21.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1264,354,781,Turkey,Government of Turkey,115,NaN,PKK,323,NaN,1,...,3,"Iraq, Turkey",640,NaN,NaN,NaN,640,"645, 640",2,21.1
1297,364,792,India,Government of India,141,NaN,Kashmir insurgents,325,NaN,1,...,3,India,750,NaN,NaN,NaN,750,750,3,21.1
1546,404,857,Pakistan,Government of Pakistan,142,NaN,TTP,356,NaN,2,...,3,Pakistan,770,NaN,NaN,NaN,770,770,3,21.1
1624,418,878,United States of America,Government of United States of America,3,Government of Afghanistan,al-Qaida,769,NaN,2,...,4,Afghanistan,2,700,NaN,NaN,2,700,5,21.1
1662,423,888,Thailand,Government of Thailand,147,NaN,Patani insurgents,365,NaN,1,...,3,Thailand,800,NaN,NaN,NaN,800,800,3,21.1